/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'cat-latte-rosewater':  '#dc8a78',
        'cat-latte-flamingo':   '#dd7878',
        'cat-latte-pink':       '#ea76cb',
        'cat-latte-mauve':      '#8839ef',
        'cat-latte-red':        '#d20f39',
        'cat-latte-maroon':     '#e64553',
        'cat-latte-peach':      '#fe640b',
        'cat-latte-yellow':     '#df8e1d',
        'cat-latte-green':      '#40a02b',
        'cat-latte-teal':       '#179299',
        'cat-latte-sky':        '#04a5e5',
        'cat-latte-sapphire':   '#209fb5',
        'cat-latte-blue':       '#1e66f5',
        'cat-latte-lavender':   '#7287fd',
        'cat-latte-text':       '#4c4f69',
        'cat-latte-subtext-1':  '#5c5f77',
        'cat-latte-subtext-0':  '#6c6f85',
        'cat-latte-overlay-2':  '#7c7f93',
        'cat-latte-overlay-1':  '#8c8fa1',
        'cat-latte-overlay-0':  '#9ca0b0',
        'cat-latte-surface-2':  '#acb0be',
        'cat-latte-surface-1':  '#bcc0cc',
        'cat-latte-surface-0':  '#ccd0da',
        'cat-latte-base':       '#eff1f5',
        'cat-latte-mantle':     '#e6e9ef',
        'cat-latte-crust':      '#dce0e8',

        'cat-frappe-rosewater': '#f2d5cf',
        'cat-frappe-flamingo':  '#eebebe',
        'cat-frappe-pink':      '#f4b8e4',
        'cat-frappe-mauve':     '#ca9ee6',
        'cat-frappe-red':       '#e78284',
        'cat-frappe-maroon':    '#ea999c',
        'cat-frappe-peach':     '#ef9f76',
        'cat-frappe-yellow':    '#e5c890',
        'cat-frappe-green':     '#a6d189',
        'cat-frappe-teal':      '#81c8be',
        'cat-frappe-sky':       '#99d1db',
        'cat-frappe-sapphire':  '#85c1dc',
        'cat-frappe-blue':      '#8caaee',
        'cat-frappe-lavender':  '#babbf1',
        'cat-frappe-text':      '#c6d0f5',
        'cat-frappe-subtext-1': '#b5bfe2',
        'cat-frappe-subtext-0': '#a5adce',
        'cat-frappe-overlay-2': '#949cbb',
        'cat-frappe-overlay-1': '#838ba7',
        'cat-frappe-overlay-0': '#737994',
        'cat-frappe-surface-2': '#626880',
        'cat-frappe-surface-1': '#51576d',
        'cat-frappe-surface-0': '#414559',
        'cat-frappe-base':      '#303446',
        'cat-frappe-mantle':    '#292c3c',
        'cat-frappe-crust':     '#232634',

        'cat-macchiato-rosewater':  '#f4dbd6',
        'cat-macchiato-flamingo':   '#f0c6c6',
        'cat-macchiato-pink':       '#f5bde6',
        'cat-macchiato-mauve':      '#c6a0f6',
        'cat-macchiato-red':        '#ed8796',
        'cat-macchiato-maroon':     '#ee99a0',
        'cat-macchiato-peach':      '#f5a97f',
        'cat-macchiato-yellow':     '#eed49f',
        'cat-macchiato-green':      '#a6da95',
        'cat-macchiato-teal':       '#8bd5ca',
        'cat-macchiato-sky':        '#91d7e3',
        'cat-macchiato-sapphire':   '#7dc4e4',
        'cat-macchiato-blue':       '#8aadf4',
        'cat-macchiato-lavender':   '#b7bdf8',
        'cat-macchiato-text':       '#cad3f5',
        'cat-macchiato-subtext-1':  '#b8c0e0',
        'cat-macchiato-subtext-0':  '#a5adcb',
        'cat-macchiato-overlay-2':  '#939ab7',
        'cat-macchiato-overlay-1':  '#8087a2',
        'cat-macchiato-overlay-0':  '#6e738d',
        'cat-macchiato-surface-2':  '#5b6078',
        'cat-macchiato-surface-1':  '#494d64',
        'cat-macchiato-surface-0':  '#363a4f',
        'cat-macchiato-base':       '#24273a',
        'cat-macchiato-mantle':     '#1e2030',
        'cat-macchiato-crust':      '#181926',

        'cat-moccha-rosewater':   '#f5e0dc',
        'cat-moccha-flamingo':    '#f2cdcd',
        'cat-moccha-pink':        '#f5c2e7',
        'cat-moccha-mauve':       '#cba6f7',
        'cat-moccha-red':         '#f38ba8',
        'cat-moccha-maroon':      '#eba0ac',
        'cat-moccha-peach':       '#fab387',
        'cat-moccha-yellow':      '#f9e2af',
        'cat-moccha-green':       '#a6e3a1',
        'cat-moccha-teal':        '#94e2d5',
        'cat-moccha-sky':         '#89dceb',
        'cat-moccha-sapphire':    '#74c7ec',
        'cat-moccha-blue':        '#89b4fa',
        'cat-moccha-lavender':    '#b4befe',
        'cat-moccha-text':        '#cdd6f4',
        'cat-moccha-subtext-1':   '#bac2de',
        'cat-moccha-subtext-0':   '#a6adc8',
        'cat-moccha-overlay-2':   '#9399b2',
        'cat-moccha-overlay-1':   '#7f849c',
        'cat-moccha-overlay-0':   '#6c7086',
        'cat-moccha-surface-2':   '#585b70',
        'cat-moccha-surface-1':   '#45475a',
        'cat-moccha-surface-0':   '#313244',
        'cat-moccha-base':        '#1e1e2e',
        'cat-moccha-mantle':      '#181825',
        'cat-moccha-crust':       '#11111b'
        
      },
    },
  },
  plugins: [require("@catppuccin/tailwindcss")],
}

